### ISSUE TITLE
incorrect cursor position and inconsistent scrolling behaviour in editor with overflow

### ISSUE THREAD

**Issue by vthriller** [ocavue/prosemirror-virtual-cursor#47]
## Exhibit A

```css
.ProseMirror {
    word-wrap: normal;
    overflow: auto;
}
```

> abc**def**ghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz

- cursor in "abc┘**def**", scrolled outside of viewport
- press →
- cursor is not scrolled into view
- press →
- viewport is scrolled to the cursor position ("**ef**ghi..."), but no cursor visible
- manually scroll to the left
- cursor is blinking at the very edge of the element, in the padding area: 
  ![image](https://github.com/user-attachments/assets/ff60f94c-3aa8-4e6f-97b7-f5d82121621d)

## Exhibit B

```css
.ProseMirror {
    overflow: auto;
}

.ProseMirror pre {
    white-space: pre;
}
```

> ```
>       console.warn(
>         `[prosemirror-virtual-cursor] Virtual cursor does not work well with marks that have inclusive set to false. Please consider removing the inclusive option from the "${mark}" mark or adding it to the "skipWarning" option.`,
>       );
> ```

- place cursor anywhere in the code block
- scroll horizontally
- use arrow keys or mouse to change cursor position
- cursor is rendered with offset (verify by typing in text)

**Comment by vthriller** [comment]
Well, it is affected by vertical overflow as well.

```css
.ProseMirror {
  max-height: 10em;
  overflow: auto;
}
```

> lorem
>
> ipsum
>
> dolor
>
> sit
>
> amet

Cursor on the last line is rendered higher than it should be:

![image](https://github.com/user-attachments/assets/0b60335f-8eee-442e-82b5-c85e27d6fd0b)
